:: Generated by: https://github.com/swagger-api/swagger-codegen.git
::

@echo off

dotnet restore src\Home_test_V1
dotnet build src\Home_test_V1
echo Now, run the following to start the project: dotnet run -p src\Home_test_V1\Home_test_V1.csproj --launch-profile web.
echo.
